version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/sendinblue-mailer # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/php:fpm-stretch # ...with this image as the primary container; this is where all `steps` will run environment:
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Install system packages
          command: sudo apt-get update && sudo apt-get -y install git
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Run tests
          command: ./vendor/bin/simple-phpunit --coverage-html build/coverage-report
      - store_artifacts:
          path:  build/coverage-report