name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run tests
      run: ./vendor/bin/simple-phpunit --coverage-html build/coverage-report

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: build/coverage-report
